# Generated by Django 5.2.5 on 2025-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelsTable',
            fields=[
                ('model_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
            ],
        ),
    ]
