# Generated by Django 5.2.5 on 2025-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_filetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
            ],
        ),
    ]
